### ISSUE TITLE
Mot manquant

### ISSUE THREAD

**Issue by Nonolanlan1007** [ValRedstone/MultiBot#3]
Il manque le mot "jours" dans le remind.js à la ligne 11 après le mot "14".

**Comment by ValDesign22** [comment]
Merci de report @Nonolanlan1007,

Si tu as d'autres questions ou des changements à dire merci de le faire içi.
Pour ce qui est des gros changements de fichiers (si ça arrive), fait une pull request.
Sinon tu peux me dire si je peux fermer l'issue.

Bonne journée

**Comment by Nonolanlan1007** [comment]
Tu peux fermer l'issue :p

**Comment by ValDesign22** [comment]
Ok
