### ISSUE TITLE
Error: Cannot find module './src/functions/encode'

### ISSUE THREAD

**Issue by ntnwlrs57** [ValRedstone/MultiBot#4]
Bonjour j'ai cette erreur en démarrant le bot et j'ai l'impression que le dossier "src" est manqaunt

**Comment by ValDesign22** [comment]
Bonjour, oui le fichier src/functions/encode.js n'est pas sur le code.

Mais le problème avec ce code c'est qu'il est complètement abandonné je n'y touche plus depuis un moment.

Bonne journée à vous.
